<ns0:test-suite xmlns:ns0="urn:model.allure.qatools.yandex.ru" start="1545657236566" stop="1545657236640">
  <name>script</name>
  <labels/>
  <test-cases>
    <test-case start="1545657236566" status="passed" stop="1545657236578">
      <name>test_login.Testlogin.test_a</name>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="15944-MainThread"/>
        <label name="host" value="MSI"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1545657236580" status="failed" stop="1545657236640">
      <name>test_login.Testlogin.test_b</name>
      <failure>
        <message>AssertionError: assert 0</message>
        <stack-trace>self = &lt;script.test_login.Testlogin object at 0x0000016308E0AA58&gt;

    def test_b(self):
        print("\n222")
&gt;       assert 0
E       assert 0

script\test_login.py:8: AssertionError</stack-trace>
      </failure>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="15944-MainThread"/>
        <label name="host" value="MSI"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
  </test-cases>
</ns0:test-suite>
